import { DM_Sans, Poppins } from 'next/font/google'
import "/public/app/dist/app.css"
import "/public/app/dist/swiper-bundle.min.css"
import {useEffect} from "react";
import {useDispatch} from "react-redux";
import {storage} from "@/storage";

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--poppins",
    display: 'swap',
})
const dm = DM_Sans({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--dm",
    display: 'swap',
})

export const metadata = {
    title: 'Rockie | Crypto Exchange Next.js Template',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    const dispatch = useDispatch()

    const getAuth = () => {

    }

    useEffect(() => {
        if (!localStorage.getItem(storage.accessToken) || !localStorage.getItem(storage.refreshToken)) {
            dispatch({type: 'authStatus', payload: {isAuth: false}})
        }
    }, []);

    return (
        <html lang="en">
            <body className={`${poppins.variable} ${dm.variable} body header-fixed`}>{children}</body>
        </html>
    )
}
